### ISSUE TITLE
04WK3: Setup Backend

### ISSUE THREAD

**Issue by GCodeON** [SoftStackFactory/memedata#3]
- [x] Setup REST API w/ loopback 
- [x] Connect MongoDB (Talk to Gera for DB info)
- [x] Setup Token authentication
- [x] Create User Model
- [x] Create Poll Model
- [x] Create Meme Model
- [x] Set relations: User has many polls, polls have many memes

**Comment by Avilpa1** [comment]
Completed setting up back end. I used my MLab account for testing purposes.
