### ISSUE TITLE
04WK3: Poll Builder

### ISSUE THREAD

**Issue by GCodeON** [SoftStackFactory/memedata#6]
Create a multi stepped meme creation form:
Step1
- [x] initiate device camera 
- [x] Add functionality to be able to select a user's stored images
- [x] add exit button to return to dashboard
Step2
- [x] Preview image chosen
- [x] Add Bottom, top, description input markup
- [x] Add functionality to add text to image
- [x] Next Button: goes to preview meme view
- [x] 2 way data binding to preview meme in real time
Step3
- [x] Add cover flow functionality  to swipe left/right and preview created memes
- [x] Add meme button that initiates step1
- [x] Next Button: goes to poll info
- [x] Add delete button to delete/edit memes
- [ ] Add card flip functionality to display meme description
Step4
- [x] Add poll title and description inputs
- [x] Add categories dropdown list
- [x] publish button markup
- [x] After reroutes to created poll history view

**Comment by Michaelpp20001** [comment]
added several issues that needed attention and checked a few off
